### PR TITLE
Add "Tidy data for librarians" lesson

### PR DESCRIPTION
**Pull request by jezcope**
Not sure what the criteria are for listing a new lesson here — happy to improve this and/or have it migrated to https://github.com/data-lessons first if need be.

### CODE REVIEW

**Comment by drjwbaker** [comment]
I'm happy for it to be added as an option. To migrate it to data-lessons we need three things:

First, we need to make sure it is clear where this lesson fits between the other lessons: where are the overlaps, where do skills here get built on elsewhere, where is the same thing being done a different way.

Second, I think we need other regular trainers to be happy to as it becomes part of 'our offer' once at data-lessons.

Third, presuming you will be a listed maintainer of the lesson, we also need someone to step up as co-maintainer (just in case you fall under a bus et cetera). Can you pull that together? Beyond that, be sure to check all the links in and around the lesson pages to check they go the right places (eg, citation) before issuing a PR.

**Comment by jezcope** [comment]
Aha, maybe it's worth having a separate "incubator" section then, for new lessons that maybe need a bit more work and need a few different instructors to try them out? That might also help reduce the number of "orphan" lessons that get developed and taught as a one off and then disappear because they're hard to find. What do you think?

**Comment by drjwbaker** [comment]
Sure. Listing lessons in development sounds good to me.

**Comment by weaverbel** [comment]
Hi @jezcope have you got an actual lesson for this tidy thing? or are you just floating the idea? I'd be interested in seeing the lesson if there is one.

**Comment by jezcope** [comment]
@weaverbel Yup, it's [right here](https://jezcope.github.io/library-spreadsheets/) and I taught it on Tuesday. :slightly_smiling_face: I can't claim much credit for it though; it's mostly a port of [datacarpentry/spreadsheet-ecology-lesson](https://github.com/datacarpentry/spreadsheet-ecology-lesson) to make it more relevant to library folks.

I'll close this PR for now and see if I have time to put together an incubator page proposal over the weekend.

**Pull request closed without merging**
