### PR TITLE
Update tags "Merger" and "Workshops" blogs

### PR DESCRIPTION
**Pull request by techieeliot**

### CODE REVIEW

**Comment by techieeliot** [comment]
Happy Hacktoberfest!

**Review by serahkiburu — CHANGES_REQUESTED** [review]
Hey @techieeliot, thank you for reading and suggesting tags to the posts in this PR. [This guide](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html#carpentries-tagathon) suggests that we leave out `Library Carpentry` as a tag as all posts on this blog are on the subject.

**Comment by serahkiburu** [comment]
for #73

**Comment by techieeliot** [comment]
Referencing the "Selecting Tags for your Carpentries Blog", noting the section ["By Carpentry"](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html#by-carpentry) and the "original source" tags. Please advise.

**Comment by techieeliot** [comment]
Sorry, confused about the By Carpentry section. Please review.

**Comment by serahkiburu** [comment]
Thanks Eliot!

**Pull request merged**
