### PR TITLE
People updated in Advisory Group, from CAC merge

### PR DESCRIPTION
**Pull request by ccronje**
CAC recently merged with AG: https://github.com/LibraryCarpentry/governance/issues/18
Pages updated:
- removed dropdown link to CAC on navigation (now People links to AG)
- added remaining CAC members to AG page and updated Liz to Co-chair (added their jpgs to files/advisory)

### CODE REVIEW

**Review by arieldeardorff — APPROVED** [review]
Thanks for making the updates Carmi!

**Comment by tracykteal** [comment]
Thanks! Since @ccronje and @arieldeardorff have reviewed and approved, we can go ahead and merge. With this update to the committee, are there also people who should have changed github permissions for this repo?

**Comment by arieldeardorff** [comment]
Hi @tracykteal can you give myself and my co-chair @ragamouf merge permissions?

**Comment by tracykteal** [comment]
done! Let me know if there are any issues.

**Pull request merged**
