### PR TITLE
Add some tags #hacktoberfest

### PR DESCRIPTION
**Pull request by paulokenza**
Add some tags

### CODE REVIEW

**Review by serahkiburu — CHANGES_REQUESTED** [review]
Hi @paulokenza, thank you for suggesting tags for this post as per #73. Please pick a maximum of three from the list you've suggested. 

Some tips from [this guide](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html):
- since all posts in this blog are about Library Carpentry, we can exclude the `Library Carpentry` and `Library Carpentries` tags
- it is also ok to not include organisation / institution names in tags

**Comment by serahkiburu** [comment]
Hi @paulokenza, checking to see if you'll have some time to make requested changes this week

**Comment by emcaulay** [comment]
This pull request is quite old, and if the tags were to support an event in 2019, I think we should cancel this pull request.

**Comment by maneesha** [comment]
@emcaulay I want to bring our comms team in on this.

@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open?

For this one, it was pending review from Serah but then it just sat. I'm ok merging or closing as you see fit.

**Comment by kmomar** [comment]
@maneesha @acrall and I decided to merge this.

**Pull request merged**
