### PR TITLE
Update home pages with lessons

### PR DESCRIPTION
**Pull request by jcoliver**
Here's a start (re: issue #21 on https://github.com/data-lessons/library-data-intro/issues). I moved what was in index.html to blog.md and updated _layouts/default.html appropriately to reflect this change.

I also updated the verbiage on about.md a bit.

This could still use some serious styling, and could even be done dynamically _a la_ the way software carpentry treats episodes. But it's a starting point for links to all the lessons in one place.

### CODE REVIEW

**Comment by jcoliver** [comment]
Hold off on this PR. Have to update some image files first...

**Comment by jcoliver** [comment]
OK, added images files to blog. Should probably fix this so image assets aren't duplicated (or triplicated, or quadruplicated), but that is a separate issue.  PR should be ready.

**Comment by drjwbaker** [comment]
@jezcope Seen as you were looking at this separately (which I assumed incorrectly was dormant, so apologies for the duplication!) could you take a look at this?

**Comment by jezcope** [comment]
Looks like you beat me to it! ;)

**Comment by drjwbaker** [comment]
Yeah, sorry. I just wanted to see what it would look like. Do your hacks look much different?

**Comment by jezcope** [comment]
No worries! I hadn't put any info on the front page so this is better. I had solved the duplicate assets problem though, so I'm just putting together a PR for that over lunch.

This may help with previewing Github Pages stuff: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by jezcope** [comment]
See #3 :smiley:

**Comment by drjwbaker** [comment]
Thanks both. Nice to have a proper landing page!

**Comment by jezcope** [comment]
Yes, I really like this summary of the lessons.

**Pull request merged**
