### PR TITLE
Moved MarcEdit lesson to Alpha

### PR DESCRIPTION
**Pull request by abigailsparling**
Moved our MarcEdit lesson out of conceptual to Alpha as it is under active development and almost complete.

This is related to [issue](https://github.com/carpentries-incubator/proposals/issues/157) in the Incubator. We are looking for community feedback and review.

### CODE REVIEW

**Comment by tobyhodges** [comment]
I think this is one that should be approved by @LibraryCarpentry/curriculum-advisors

**Comment by maneesha** [comment]
Bump @LibraryCarpentry/curriculum-advisors

**Comment by maneesha** [comment]
Bump @LibraryCarpentry/curriculum-advisors

**Comment by jenmawe** [comment]
> Bump @LibraryCarpentry/curriculum-advisors

@maneesha Abigail and I were wondering if you are waiting for your next meeting to determine if our lesson can move to the next stage. Is there anything else that we need to do on our end? I have to admit that it's been challenging to find information on the steps to get a lesson out of draft and into alpha.

**Comment by maneesha** [comment]
@jenmawe  I think the question about how to move a lesson out of draft and into alpha can best be answered by @tobyhodges  but he has also noted above that this should be approved by  @LibraryCarpentry/curriculum-advisors.

**Comment by PhilReedData** [comment]
Hi everyone, I've put this on the agenda for the curriculum advisory committee to discuss at our meeting next week. Apologies for the slow reply.

**Comment by jenmawe** [comment]
Abigail and I just weren't sure this was the correct way to do this. Thank you @PhilReedData for the update.

**Comment by PhilReedData** [comment]
Hi everyone, I'm delighted to say that I will be moving the lesson to the Extended Curriculum section and the CAC are happy to change the status to alpha. I will let you make the status change in the repo itself and I will change the LC website.

Question: Who are the current maintainers? We had Owen Stephens (lead), Jennifer Eustis, Abigail Sparling, is that correct? The recent survey of lesson maintainers came back with no replies for MarcEdit. Perhaps you didn't get that survey invite?

We have some comments around the next steps before moving to beta status:

1. The instructor notes page is currently blank, perhaps you can include some guidance for delivery here.
2. The instructor view menu takes you to a page including a copy of the entire previous version of this lesson. What reason is there to include it here? I suggest that content is removed or hosted elsewhere, unless you have a reason we can understand for including it.
3. Has this lesson been taught yet, and do you have any feedback on that?

**Comment by jenmawe** [comment]
> Hi everyone, I'm delighted to say that I will be moving the lesson to the Extended Curriculum section and the CAC are happy to change the status to alpha. I will let you make the status change in the repo itself and I will change the LC website.
> 
> Question: Who are the current maintainers? We had Owen Stephens (lead), Jennifer Eustis, Abigail Sparling, is that correct? The recent survey of lesson maintainers came back with no replies for MarcEdit. Perhaps you didn't get that survey invite?
> 
> We have some comments around the next steps before moving to beta status:
> 
>     1. The instructor notes page is currently blank, perhaps you can include some guidance for delivery here.
> 
>     2. The instructor view menu takes you to a page including a copy of the entire previous version of this lesson. What reason is there to include it here? I suggest that content is removed or hosted elsewhere, unless you have a reason we can understand for including it.
> 
>     3. Has this lesson been taught yet, and do you have any feedback on that?

Hi @PhilReedData ,

Thank you for the update. This has been a labor of love indeed. I'm definitely happy that we are now in the alpha stage. For your questions:

1. Current maintainers: It is myself, Abigail and Owen. 
2. Maintainer emails: I know that I haven't received some surveys in the past. I don't remember seeing anything about the question for the survey. Perhaps it didn't make it my way or to Abigail or Owen as well. Would it be possible to resend that survey? Also would it be possible to put us on the list to get the survey? 
3. Instructor notes page: We just migrated to workbench. We'll be filling out this area for the instructor. We also plan on looking at our images and seeing which we really need or not.
4. Instructor view page: This is new for us in workbench. We'll be cleaning this up as well.
5. Taught?: I have used material for this to teach and only cited it as a pre-alpha lesson. We put in a submission to teach a half day workshop in October. There is also a plan to teach this later on this summer as well as part of our tests. For teaching, we are really interested in getting feedback from other instructors on the content. 

Again thank you and the curriculum advisory committee.

**Comment by tobyhodges** [comment]
> Maintainer emails: I know that I haven't received some surveys in the past. I don't remember seeing anything about the question for the survey. Perhaps it didn't make it my way or to Abigail or Owen as well. Would it be possible to resend that survey? Also would it be possible to put us on the list to get the survey?

I have added @jenmawe and @abigailsparling to the Maintainers channell on The Carpentries Slack workspace, and added Abigail to [the Maintainers mailing list on TopicBox](https://carpentries.topicbox.com/groups/maintainers/). @ostephens was already a member of both, and Jennifer was already a member on the mailing list.

@jenmawe: perhaps you were subscribed with an old email address that is no longer active/that you do not have access to anymore (e.g. old institutional email)? If so, you could log into our community database, AMY, and update the details in your profile? (To change the primary email address associated with the account, you will need to send a request by email to team at carpentries dot org)

**Comment by tobyhodges** [comment]
@PhilReedData it sounds like you will be working up another PR to move where this lesson appears in the LC lesson listing. Would you like me to merge this PR first, or do you expect your PR to supersede this one?

**Comment by jenmawe** [comment]
> > Maintainer emails: I know that I haven't received some surveys in the past. I don't remember seeing anything about the question for the survey. Perhaps it didn't make it my way or to Abigail or Owen as well. Would it be possible to resend that survey? Also would it be possible to put us on the list to get the survey?
> 
> I have added @jenmawe and @abigailsparling to the Maintainers channell on The Carpentries Slack workspace, and added Abigail to [the Maintainers mailing list on TopicBox](https://carpentries.topicbox.com/groups/maintainers/). @ostephens was already a member of both, and Jennifer was already a member on the mailing list.
> 
> @jenmawe: perhaps you were subscribed with an old email address that is no longer active/that you do not have access to anymore (e.g. old institutional email)? If so, you could log into our community database, AMY, and update the details in your profile? (To change the primary email address associated with the account, you will need to send a request by email to team at carpentries dot org)

Thanks @tobyhodges. I don't think I've been to the new AMY or Amy in some time. I'll do that once I return from my conference. Thank you also for making sure all of us maintainer are on the correct lists.

**Comment by maneesha** [comment]
Following up on this. Should we merge this or wait for a new PR? 

> @PhilReedData it sounds like you will be working up another PR to move where this lesson appears in the LC lesson listing. Would you like me to merge this PR first, or do you expect your PR to supersede this one?

**Comment by PhilReedData** [comment]
Hi all, sorry for slow replies. Previously, I did not realise that the website changes were included within this PR. I think this one will do everything necessary to update the LC website. I'll merge it now.

**Pull request merged**
