### PR TITLE
LC Governance Updates

### PR DESCRIPTION
**Pull request by tobyhodges**
- Adds the LC Governance Committee to a new "community governance" page on the website
- Adds the CAC to the "governance" page as well
- Updates links and language elsewhere on the site to reflect these changes
- Updates the membership of both committees

### CODE REVIEW

**Review by jt14den — APPROVED** [review]
Looked good to me @tobyhodges. Thanks.

**Comment by Jaredabera** [comment]
This looks good to me @tobyhodges. Thanks, and keep up the good work.

**Comment by maneesha** [comment]
@tobyhodges  would you also like to see approval from @egrguric  before merging?

**Comment by maneesha** [comment]
Bump @tobyhodges  is this ok to merge or do you still want everyone's review?

**Comment by tobyhodges** [comment]
Thanks for the reminder @maneesha It's important that the website is updated, so I will merge without @egrguric's review. Eka, please open an issue or comment on this thread if you would request any changes.

**Comment by egrguric** [comment]
Hi folks, this looks good to me too! I've been travelling without steady internet for a few weeks, sorry for the slow response! Thanks for getting this sorted @tobyhodges.

**Pull request merged**
