### PR TITLE
Add blog post regarding reuse of LC lessons

### PR DESCRIPTION
**Pull request by konrad**
Add blog post regarding reuse of LC lesson written by three LC members.

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @konrad 
Blog posts are reviewed by @serahrono  and @kmomar. They had been assigned earlier and I'm tagging them now.

**Comment by konrad** [comment]
Thanks, @maneesha!

**Comment by kmomar** [comment]
Merging now!

**Comment by konrad** [comment]
:tada: thanks, @kmomar

**Pull request merged**
