### PR TITLE
Iniital draft of post-call post

### PR DESCRIPTION
**Pull request by weaverbel**
This is an attempt to provide a very brief summary of the recent calls. People who want more details can read through the etherpad which has been linked from this post.

People don't have to review but I didn't want to merge this without people seeing it and possibly suggesting changes. So ... over to you !

@drjwbaker Feel free to add the bit about you stepping away a bit if you want to - I didn't want to include that without asking you first.

### CODE REVIEW

**Comment by drjwbaker** [comment]
https://github.com/LibraryCarpentry/librarycarpentry.github.io/pull/39

**Comment by pitviper6** [comment]
Looks good!  Only thing I might add is that the IMLS grant also supports fostering local communities of new instructors in underserved areas such as the Southeast US.

Also, I didn't realize we'd settled on a number with the steering committee. Was that decided in the first call?  I don't have a problem with it at all, I just don't remember the decision.

**Comment by weaverbel** [comment]
I thought we ended up with five to have reps from the US, UK, Australia/NZ, (South) Africa and Europe - but maybe we didn't actually decide - maybe I just inferred that. @pitviper6

**Comment by richyvk** [comment]
Typo line 18: "This theme is designed for projects rather than for blogs but, with some tweaking, this should not **BE** a problem"

Also, richyvk.me is https now, so you cahange change that link to https://www.richyvk.me/library-carpentry-redesign/ :)

Line 26: finish modules -> finish lessons?

Otherwise, looks great to me.

**Comment by weaverbel** [comment]
Changes all incorporated - are we good to merge?

cheers
Belinda

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by ccronje** [comment]
Thanks Belinda 👍

**Pull request merged**
