### PR TITLE
add new maintainer

### PR DESCRIPTION
**Pull request by ErinBecker**

### CODE REVIEW

**Comment by ErinBecker** [comment]
@kmomar @zkamvar  - I don't know why the checks are failing. All I did was add one name to the lesson table. Please help!

**Comment by zkamvar** [comment]
It looks like the yaml validator is getting upset at a post from 2019:

```
File : _posts/2019/06/2019-06-25-developing-data-skills.md, error: (_posts/2019/06/2019-06-25-developing-data-skills.md): did not find expected ',' or ']' while parsing a flow sequence at line 7 column 7
```

I'll have a look and see what's happening on line 7.

**Comment by zkamvar** [comment]
OH, it looks like François fixed it in https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/2f8daa22e586d7636aadb177fdc046138e4ecbc4

**Comment by zkamvar** [comment]
The checks are failing to to an unrelated error that is fixed. I'm going to merge this. 

For full context and a timeline: 

The error originally appeared in #78, but it went undetected because the fork was made in 2019, which did not have the automated checks available (which were introduced in October 2020 with https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/98c4e2ef36b79fd937402d15a89ed8a4735de932). 

PR #78 was only merged yesterday with the yaml error still undetected: https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/e94becf54b1e87d83ad9efff4864accc76c83d93

Erin created this PR from a point in the repository where the erroneous yaml was present.

François fixed it on the main branch: https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/2f8daa22e586d7636aadb177fdc046138e4ecbc4

Despite the fix Erin's fork is still throwing the error because it has not yet received the fix.

**Comment by ErinBecker** [comment]
Thanks a million @zkamvar!!

**Pull request merged**
