### PR TITLE
Improved introduction for librarians

### PR DESCRIPTION
**Pull request by jezcope**
Not necessarily ready to merge yet — comments welcome. Addresses #7

### CODE REVIEW

**Comment by drjwbaker** [comment]
Works for me.

**Comment by richyvk** [comment]
Intro paragraph is great. Much clearer now what LC is all about.

**Comment by drjwbaker** [comment]
Merging this because I need to edit it for Monday. Of course, continue discussing at https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/7

**Comment by drjwbaker** [comment]
Merging this because I need to edit it for Monday. Of course, continue discussing at https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/7

**Pull request merged**
