### PR TITLE
Website reorganization

### PR DESCRIPTION
**Pull request by maneesha**
This begins the reorganization of the Library Carpentry website to remove all content that is not specific to LC workshops or lessons/curricula.

### CODE REVIEW

**Comment by maneesha** [comment]
Need to resolve what to do with multiple governance/advisory pages:

- https://librarycarpentry.org/team/ - LC Governance Group - in 2019 became the Advisory Group
- https://librarycarpentry.org/advisory/ - Advisory - is this active? Lists goals from 2021-22
- https://librarycarpentry.org/governance/ - Another Governance group

**Comment by chennesy** [comment]
Thanks, @maneesha!

Re: LC governance/teams: The [LC Curriculum Advisory Committee](https://github.com/LibraryCarpentry/curriculum-advisors) and the [LC Governance Committee](https://librarycarpentry.org/governance/) recently decided to merge. Currently active on the roster, who are meeting under the banner of LC-CAC: Tim Dennis, Eka Grguric, Cody Hennesy, Yared Abera Ergu, and Annajiat Alim Rasel. We'll be recruiting new members, so roles/members are likely to be fluid for a bit.  

These two groups are no longer active:
- https://librarycarpentry.org/team/
- https://librarycarpentry.org/advisory/ 

So maybe we update one page to list the LC-CAC and Governance members together? Adding @jt14den and @egrguric for thoughts...

**Comment by maneesha** [comment]
I've discussed this with @tobyhodges.  We will keep https://librarycarpentry.org/governance/ and archive the other pages.

**Comment by jt14den** [comment]
Thanks @maneesha! Looks good. We can work on updating the Gov/CAC page.

**Pull request merged**
