### PR TITLE
Adding new members to the advisory group page

### PR DESCRIPTION
**Pull request by ragamouf**
Here's the new members and their contact details for the advisory group members page. Let me know if the images look ok or if any need further edits. I haven't worked out how to preview my own updates outside of the yaml.

### CODE REVIEW

**Comment by libcce** [comment]
Hi @ragamouf the build seems to be failing. Some of the yaml may be off but also there seem to be multiple (competing) file changes in this PR. You can update the PR or I can have a crack at it if you would like? I have the info so I can submit a separate PR. This is bringing back memories re: temperamental yaml.

**Comment by tobyhodges** [comment]
I tracked the problem down and fixed it in c017b2d. However, my local build shows missing headshot images for many of the new members.

**Comment by maneesha** [comment]
The build looks like it works now but as @tobyhodges  pointed out, images for the new group members are missing.  
Rather than keeping photos in this repo, I would recommend doing what we do on pages like https://carpentries.org/instructors/ where the photo is pulled from the GitHub profile, with a placeholder photo if the user does not have a GitHub account.  Almost  all LC advisory group members have a GitHub account.

**Comment by maneesha** [comment]
Follow up to my comment above -- we can either have the new advisory group members upload images to this repo, or I can edit the page to use the GitHub images.  Does the advisory group have preferences about what images they'd like to use?

**Comment by ragamouf** [comment]
@maneesha your recommendation about following the instructors convention is a good idea, but not all LCAG members are instructors. Would that be a problem? I have a workshop later today, but will try to apply my head to this tomorrow. Thanks @libcce and @tobyhodges for your help!

**Comment by maneesha** [comment]
Not a problem - people don't need to be Instructors. The page  I linked to was just an example for what things look like.

**Pull request merged**
